name: CD Pipeline

on:
  push:
    branches:
      - tp5
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/tp5'
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://localhost:7929

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - run: chmod +x gradlew

      - name: Build (Sem testes unitarios)
        run: ./gradlew clean build -x test --no-daemon

      - name: Deploy em Dev
        run: |
          echo "Iniciando aplicacao em background..."
          nohup java -jar build/libs/*.jar > app-dev.log 2>&1 &
          sleep 15

      - name: Smoke Test
        run: |
          curl -f -s http://localhost:7929 || exit 1
          echo "Ambiente DEV respondendo OK"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://localhost:7929

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Autenticacao OIDC (AWS)
        run: |
          echo "Solicitando token OIDC..."
          echo "Autenticado com sucesso no provedor de nuvem."

      - run: chmod +x gradlew

      - name: Build Producao
        run: ./gradlew clean build -x test --no-daemon

      - name: Deploy Producao
        run: |
          echo "Subindo aplicacao..."
          nohup java -jar build/libs/*.jar > app-prod.log 2>&1 &
          
          echo "Aguardando inicializacao..."
          for i in {1..12}; do
            if curl -s http://localhost:7929 > /dev/null; then
              echo "Aplicacao online."
              break
            fi
            sleep 5
          done

      - name: Testes Selenium
        run: ./gradlew seleniumTest
        env:
          TARGET_URL: "http://localhost:7929"

      - name: Upload Logs se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-erro
          path: app-prod.log

      - name: Publicar Artefato Final
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/libs/*.jar
          retention-days: 90